version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: ecommerce_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ecommerce_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ecommerce_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ecommerce_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - ecommerce_network

  user-service:
    build: ./backend/user-service
    container_name: user_service
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: user_service_db
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
    ports:
      - "8001:8001"
    depends_on:
      - mysql
    networks:
      - ecommerce_network

  product-service:
    build: ./backend/product-service
    container_name: product_service
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: product_service_db
    ports:
      - "8002:8002"
    depends_on:
      - mysql
    networks:
      - ecommerce_network

  order-service:
    build: ./backend/order-service
    container_name: order_service
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: order_service_db
    ports:
      - "8003:8003"
    depends_on:
      - mysql
    networks:
      - ecommerce_network

  api-gateway:
    build: ./backend/api-gateway
    container_name: api_gateway
    ports:
      - "8000:8000"
    depends_on:
      - user-service
      - product-service
      - order-service
    networks:
      - ecommerce_network

  frontend:
    build: ./frontend
    container_name: ecommerce_frontend
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway
    networks:
      - ecommerce_network

volumes:
  mysql_data:

networks:
  ecommerce_network:
    driver: bridge