prometheus:
  service:
    type: NodePort
    nodePort: 30909
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    retention: 7d

grafana:
  enabled: true
  adminPassword: admin
  service:
    type: NodePort
    nodePort: 30900
  persistence:
    enabled: false
  additionalDataSources: []
  testFramework:
    enabled: false

alertmanager:
  enabled: true

# Enable service monitors for common components
kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

prometheusOperator:
  enabled: true
