{{- if .Values.apiGateway.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ecommerce-app.fullname" . }}-api-gateway
  labels:
    app: api-gateway
spec:
  replicas: {{ .Values.apiGateway.replicaCount }}
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: "{{ .Values.apiGateway.image.repository }}:{{ .Values.apiGateway.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8000
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ecommerce-app.fullname" . }}-api-gateway
spec:
  selector:
    app: api-gateway
  ports:
  - port: {{ .Values.apiGateway.service.port }}
    targetPort: 8000
    {{- if eq .Values.apiGateway.service.type "NodePort" }}
    nodePort: {{ .Values.apiGateway.service.nodePort }}
    {{- end }}
  type: {{ .Values.apiGateway.service.type }}
{{- end }}
