{{- if .Values.orderService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ecommerce-app.fullname" . }}-order-service
  labels:
    app: order-service
spec:
  replicas: {{ .Values.orderService.replicaCount }}
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: "{{ .Values.orderService.image.repository }}:{{ .Values.orderService.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8003
        env:
        - name: DB_HOST
          value: {{ include "ecommerce-app.fullname" . }}-mysql
        - name: DB_USER
          value: root
        - name: DB_PASSWORD
          value: {{ .Values.mysql.rootPassword }}
        - name: DB_NAME
          value: {{ .Values.orderService.env.dbName }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ecommerce-app.fullname" . }}-order-service
spec:
  selector:
    app: order-service
  ports:
  - port: {{ .Values.orderService.service.port }}
    targetPort: 8003
  type: {{ .Values.orderService.service.type }}
{{- end }}
