{{- if .Values.userService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ecommerce-app.fullname" . }}-user-service
  labels:
    app: user-service
spec:
  replicas: {{ .Values.userService.replicaCount }}
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: "{{ .Values.userService.image.repository }}:{{ .Values.userService.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8001
        env:
        - name: DB_HOST
          value: {{ include "ecommerce-app.fullname" . }}-mysql
        - name: DB_USER
          value: root
        - name: DB_PASSWORD
          value: {{ .Values.mysql.rootPassword }}
        - name: DB_NAME
          value: {{ .Values.userService.env.dbName }}
        - name: GOOGLE_CLIENT_ID
          value: {{ .Values.userService.env.googleClientId }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ecommerce-app.fullname" . }}-user-service
spec:
  selector:
    app: user-service
  ports:
  - port: {{ .Values.userService.service.port }}
    targetPort: 8001
  type: {{ .Values.userService.service.type }}
{{- end }}
